name: Test Python Code

on: [push, pull_request]

jobs:
  test:

    runs-on: [self-hosted, linux]
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Pytest Install
      run: |
         pip install pytest
         pytest
