name: Test LWA EPIC

on: [push, pull_request]

jobs:
  test:

    runs-on: [self-hosted, linux, x64]
    env:
      ENV_NAME: epic
      WORKDIR: /data5/epic-actions-runner/_work/LWA_EPIC
      PYTHON: ${{ matrix.python-version }}
      OS: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6]

    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1

    - uses: conda-incubator/setup-miniconda@v2.0.0
      with:
        auto-update-conda: true
        miniconda-version: "latest"
        python-version: ${{ matrix.python-version }}
        environment-file: config/${{ env.ENV_NAME }}.yml
        activate-environment: ${{ env.ENV_NAME }}

    - name: Install bifrost
      run: |
        export PATH="$WORKDIR/LWA_EPIC/3/condabin:$PATH"
        export PATH=/usr/local/cuda-10.2/bin:$PATH
        export LD_LIBRARY_PATH=/usr/local/cuda-10.2/lib64:$LD_LIBRARY_PATH
        cd $WORKDIR
        git clone --branch ibverb-support https://github.com/epic-astronomy/bifrost.git
        cd bifrost
        cp $WORKDIR/LWA_EPIC/config/ASU_user.mk user.mk
        conda activate ${ENV_NAME}
        make -j 32
        make install INSTALL_LIB_DIR="$WORKDIR/miniconda/envs/${ENV_NAME}/lib" INSTALL_INC_DIR="$WORKDIR/miniconda/envs/${ENV_NAME}/include" PYINSTALLFLAGS="--prefix=$WORKDIR/miniconda/envs/${ENV_NAME}"

    - name: Install
      run: |
        export PATH="$WORKDIR/LWA_EPIC/3/condabin:$PATH"
        conda activate ${ENV_NAME}
        pip install .

    - name: Pytest Install
      run: |
        export PATH="$WORKDIR/LWA_EPIC/3/condabin:$PATH"
        conda activate ${ENV_NAME}
        pytest
    #
    # - name: Clean up
    #   if: always()
    #   run: |
    #     cd $HOME
    #     rm -rf $WORKDIR/*
